version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=digitalsys
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d digitalsys"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - digitalsys_network

  web:
    container_name: "django"
    image: python:latest
    command: ./setup_dev.sh
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=loans_for_good.settings
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_USERNAME
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - digitalsys_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - digitalsys_network

  celery:
    build: .
    container_name: celery
    command: celery -A celery_tasks worker -Q default -l info -Ofair -E
    volumes:
      - ./:/home/app
    networks:
      - digitalsys_network
    depends_on:
      - db
      - redis

networks:
  digitalsys_network:
